title: Rosa Evelin Guzman Valencia
logo: foto.jpg
description: Â¡Hola! Te doy la bienvenida a mi portafolio de proyectos de QA Enginner.
show_downloads: false
github: https://github.com/RosaEGV/RosaEGV.git
#google_analytics:
theme: jekyll-theme-minimal
